import localFont from "next/font/local";
import "./globals.scss";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

const satoshi = localFont({
    src: [
        {
            path: "./fonts/Satoshi-Light.woff",
            weight: "300",
        },
        {
            path: "./fonts/Satoshi-Regular.woff",
            weight: "400",
        },
        {
            path: "./fonts/Satoshi-Medium.woff",
            weight: "500",
        },
        {
            path: "./fonts/Satoshi-Bold.woff",
            weight: "700",
        },
        {
            path: "./fonts/Satoshi-Black.woff",
            weight: "900",
        },
    ],
    variable: "--font-satoshi",
});

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={`${geistSans.variable} ${geistMono.variable} ${satoshi.variable}`}>
                {children}
            </body>
        </html>
    );
}
